generator:
  class:              sfDoctrineAdminGenerator
  param:
    model_class:      sfGuardUser
    theme:            default
    
    list:
      title:   User list
      display: [ =username, created_at, last_login ]
      filters: [ username ]

    edit:
      title:   Edit "%%username%%" user
      fields:
        username:                 { name: 'Username' }
        password:                 { name: 'Password' }
        password_bis:             { name: 'Password (again)' }
        users_groups:             { name: 'Groups/Roles', type: doctrine_admin_double_list, params: associated_label=Assigned unassociated_label=Available }
        users_permissions:        { name: 'Permissions', type: doctrine_admin_double_list, params: associated_label=Assigned unassociated_label=Available }
        last_login:               { name: 'Last Login', type: plain }
        is_active:                { name: 'Active?' }
      display:
        "NONE":                   [ username, _password, _password_bis ]
        "Information":            [ last_login ]
        "Permissions and Groups": [ is_active, users_groups, users_permissions ]
