<?php include('schemaConfig.php') ?>
sfGuardUser:
  tableName: <?php echo $config['user_table']."\n"; ?>
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    username:
      type: string
      size: 128
      notnull: true
    algorithm:
      type: string
      size: 128
      default: sha1
      notnull: true
    salt:
      type: string
      size: 128
      notnull: true
    password:
      type: string
      size: 128
      notnull: true
    created_at:
      type: timestamp
      size: null
    last_login:
      type: timestamp
      size: null
    is_active:
      type: boolean
      size: null
      default: true
      notnull: true
    is_super_admin:
      type: boolean
      size: null
      default: false
      notnull: true

sfGuardUserGroup:
  tableName: <?php echo $config['user_group_table']."\n"; ?>
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    group_id:
      type: integer
      size: 4
      foreignClass: sfGuardGroup
      foreignReference: id
      localName: users
      counterpart: user_id
      foreignName: sfGuardGroup
    user_id:
      type: integer
      size: 4
      foreignClass: sfGuardUser
      foreignReference: id
      localName: groups
      counterpart: group_id
      foreignName: sfGuardUser

sfGuardUserPermission:
  tableName: <?php echo $config['user_permission_table']."\n"; ?>
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    user_id:
      type: integer
      size: 4
      foreignClass: sfGuardUser
      foreignReference: id
      localName: permissions
      counterpart: permission_id
      foreignName: sfGuardUser
    permission_id:
      type: integer
      size: 4
      foreignClass: sfGuardPermission
      localName: users
      counterpart: user_id

sfGuardGroup:
  tableName: <?php echo $config['group_table']."\n"; ?>
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    name:
      type: string
      size: 255
      notnull: true
    description:
      type: string
      size: 4000

sfGuardGroupPermission:
  tableName: <?php echo $config['group_permission_table']."\n"; ?>
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    group_id:
      type: integer
      size: 4
      foreignClass: sfGuardGroup
      localName: permissions
      counterpart: permission_id
    permission_id:
      type: integer
      size: 4
      notnull: true
      foreignClass: sfGuardPermission
      localName: groups
      counterpart: group_id

sfGuardPermission:
  tableName: <?php echo $config['permission_table']."\n"; ?>
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    name:
      type: string
      size: 255
      notnull: true
    description:
      type: string
      size: 4000

sfGuardRememberKey:
  tableName: <?php echo $config['remember_key_table']."\n"; ?>
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    user_id:
      type: integer
      size: 4
      primary: true
      foreignClass: sfGuardUser
      foreignName: user
      localName: remember_key
      cascadeDelete: true
    remember_key:
      type: string
      size: 32
    ip_address:
      type: string
      size: 15
      primary: true
    created_at:
      type: timestamp
      size: null
