sfGuardRememberKey:
  tableName: sf_guard_remember_key
  columns:
    user_id:
      type: integer
      size: 11
      primary: true
      foreignClass: sfGuardUser
      foreignName: user
      localName: remember_key
      onDelete: cascade
    remember_key:
      type: string
      size: 32
    ip_address:
      type: string
      size: 15
      primary: true
    created_at:
      type: timestamp
      size: null
