sfGuardUser:
  tableName: sf_guard_user
  columns:
    username:
      type: string
      size: 128
      notnull: true
    algorithm:
      type: string
      size: 128
      default: sha1
      notnull: true
    salt:
      type: string
      size: 128
      notnull: true
    password:
      type: string
      size: 128
      notnull: true
    created_at:
      type: timestamp
      size: null
    last_login:
      type: timestamp
      size: null
    is_active:
      type: boolean
      size: null
      default: true
      notnull: true
    is_super_admin:
      type: boolean
      size: null
      default: false
      notnull: true
