sfGuardGroupPermission:
  tableName: sf_guard_group_permission
  columns:
    group_id:
      type: integer
      size: 11
      primary: true
      foreignClass: sfGuardGroup
      localName: groups_permissions
      counterpart: permission_id
    permission_id:
      type: integer
      size: 11
      notnull: true
      primary: true
      foreignClass: sfGuardPermission
      localName: groups
      counterpart: group_id
