sfGuardUserPermission:
  tableName: sf_guard_user_permission
  columns:
    user_id:
      type: integer
      size: 11
      primary: true
      foreignClass: sfGuardUser
      localName: users_permissions
      counterpart: permission_id
    permission_id:
      type: integer
      size: 11
      primary: true
      foreignClass: sfGuardPermission
      localName: users
      counterpart: user_id
